Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - config/routes.rb
Metrics/BlockLength:
  Exclude:
    - **/*.rake

AllCops:
  Exclude:
    - node_modules/**/*
    - script/**/*
    - bin/**/*
    - db/**/*
